### ISSUE TITLE
Problems compiling Linpack

### ISSUE THREAD

**Issue by simonhennessey** [EPCCed/wee_archlet#4] opened 2018-03-20 18:59 UTC
Hi,  I've got the cluster working but I can't get linpack to compile. I'm hitting two problems and having no success in fixing them.  I'm using the latest version of Raspbian on new Pi3 Model B.  
I get two errors from make arch=rpi:  'linker input file unused' and 'undefined reference to symbol 'pthread_create@@GLIBC_2.4'':  See:

mpicc -o HPL_pddriver.o -c -DAdd_ -DF77_INTEGER=int -DStringSunStyle  -I/home/shared_dir/linpack/hpl-2.2/include -I/home/shared_dir/linpack/hpl-2.2/include/r$
gcc: warning: /usr/lib/atlas-base/libf77blas.a: linker input file unused because linking not done
gcc: warning: /usr/lib/atlas-base/libatlas.a: linker input file unused because linking not done
mpicc -o HPL_pdinfo.o -c -DAdd_ -DF77_INTEGER=int -DStringSunStyle  -I/home/shared_dir/linpack/hpl-2.2/include -I/home/shared_dir/linpack/hpl-2.2/include/rpi$
gcc: warning: /usr/lib/atlas-base/libf77blas.a: linker input file unused because linking not done
gcc: warning: /usr/lib/atlas-base/libatlas.a: linker input file unused because linking not done
mpicc -o HPL_pdtest.o -c -DAdd_ -DF77_INTEGER=int -DStringSunStyle  -I/home/shared_dir/linpack/hpl-2.2/include -I/home/shared_dir/linpack/hpl-2.2/include/rpi$
gcc: warning: /usr/lib/atlas-base/libf77blas.a: linker input file unused because linking not done
gcc: warning: /usr/lib/atlas-base/libatlas.a: linker input file unused because linking not done
mpif77  -o /home/shared_dir/linpack/hpl-2.2/bin/rpi/xhpl HPL_pddriver.o         HPL_pdinfo.o           HPL_pdtest.o /home/shared_dir/linpack/hpl-2.2/lib/rpi/$
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libmpich.a(lib_libmpich_la-mpiu_thread_posix.o): undefined reference to symbol 'pthread_create@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:76: recipe for target 'dexe.grd' failed
make[2]: *** [dexe.grd] Error 1
make[2]: Leaving directory '/home/shared_dir/linpack/hpl-2.2/testing/ptest/rpi'
Make.top:64: recipe for target 'build_tst' failed
make[1]: *** [build_tst] Error 2
make[1]: Leaving directory '/home/shared_dir/linpack/hpl-2.2'
Makefile:72: recipe for target 'build' failed
make: *** [build] Error 2

I had previously had problems with the LAdir setting giving filenames of the form /usr/lib/atlas-base//libf77blas.a (with // ) so have set LAdir to /usr/lib/atlas-base  (no final / ).  

Any help would be much appreciated.
Simon

**Comment by gpsgibb** [comment] 2018-03-21 12:15
Hi Simon,

Were you building Linpack on one of the Pis, or on an external shared drive? That sometimes causes linking errors.

It could also be a case of some libraries not being installed. Could you try `sudo apt-get install mpich-dev` because it may be that your version of raspbian separates the MPI build into two packages (mpich, and mpich-dev) which for some reason are not both installed during `sudo apt-get install mpich`.

Let me know if any of that makes a difference.

Regards,

Gordon

**Comment by simonhennessey** [comment] 2018-03-22 13:47
Hi Gordon

Thanks for your prompt response. 

 

I was building Linpack following the instructions in https://epcced.github.io/wee_archlet/. 

 

I tried sudo apt-get install mpich-dev and got an error ‘unable to locate package mpich-dev’.  

 

I have successfully run the test:

mpiexec -n 20 -f hostfile ./hello

It is just the setup of Linpack that is failing. 

 

Any help would be much appreciated.   

 

Best regards

 

Simon

**Comment by gpsgibb** [comment] 2018-03-22 16:00
Hi Simon,

I assume you're using Raspbian Stretch? We haven't tested our instructions on this version so there may be issues. We'll try to get our hands on a spare board and install stretch on it and see if we can reproduce your problem.

Hopefully we'll have some answers by next week.

Cheers,

Gordon

**Comment by simonhennessey** [comment] 2018-03-22 16:27
Hi Gordon

Yes, that’s right.  I’m new to this so didn’t initially appreciate the differences between Stretch and Jessie etc.  

I’ve also had problems with the dhcp server but have been using the IP addresses from my router successfully, so far.  

I think that stretch changed the way network connections were named but on my system they still seem to be eth0 and wlan0, which I think can be an option.  

 

If you could try and stretch and let me know what you find that would be great.

 

Many thanks

 

Simon

**Comment by agngrant** [comment] 2018-04-20 11:04
Hi,

Apologies for the late reply  - the error appears to be centred around this problem:
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libmpich.a(lib_libmpich_la-mpiu_thread_posix.o): undefined reference to symbol 'pthread_create@@GLIBC_2.4'

In the Make.rpi file - add to the line: HPL_LIBS -lpthread
It should now read:
HPL_LIBS     = $(HPLlib) $(LAlib) $(MPlib) -lpthread

If you can try this and let us know. This is what solved it on our test.

regardsm
alistair.

**Comment by simonhennessey** [comment] 2018-05-02 21:27
Hi Alistair

That seems to have fixed it – many thanks for your help.  

 

Regards

Simon

**Comment by agngrant** [comment] 2018-05-03 14:09
Issue appears to have been addressed - closing 03/05/2018

**Closed as completed by agngrant** 2018-05-03 14:09 UTC
